language: csharp
sudo: required 
os: linux
dist: trusty
mono: none
dotnet: 2.2
install:
- dotnet restore 4th-semester/Homework2/
script:
- dotnet build 4th-semester/Homework2/Homework2.sln
- dotnet test 4th-semester/Homework2/Homework.Tests/Homework.Tests.fsproj
