language: csharp
sudo: required 
os: linux
dist: xenial
mono: none
dotnet: 2.2
install:
- dotnet restore 4th-semester/Test1/
script:
- dotnet build 4th-semester/Test1/Test1.sln
- dotnet test 4th-semester/Test1/
