language: csharp
sudo: required 
os: linux
dist: xenial 
mono: none
dotnet: 2.2
install:
- dotnet restore 4th-semester/Test2/
script:
- dotnet build 4th-semester/Test2/Test2.sln
- dotnet test 4th-semester/Test2/Test2.sln
